"""
Milvus Lite hybrid (dense + BM25) vector store helper.

By default Milvus Lite runs embedded, no server to install — the "database"
is just a local file (hybrid_rag.db). Set MILVUS_ADDRESS=http://host:19530 to
point the exact same code at Milvus Standalone (see docker-compose.yml).
One collection holds these fields per row:
  - the raw text (for text docs), a Gemini transcript (audio) or a Gemini
    description incl. visible/spoken text (image, video)
  - modality: "text", "audio", "image" or "video" — so you know where a result came from
  - source: original filename, for traceability
  - a dense vector (Gemini embedding)  -> for semantic/meaning search
  - a sparse vector, auto-generated by Milvus's built-in BM25 function
    from the "text" field                -> for exact keyword search

Multimodal note: Milvus itself only stores/searches vectors — it doesn't
"understand" audio. The multimodal step happens upstream in Gemini:
audio clips are transcribed (gemini_client.transcribe_audio), images and
videos are described (gemini_client.describe_image / describe_video), and
that text is what gets embedded
and BM25-indexed here, just like any other document. This keeps ONE retrieval
pipeline for all modalities.

hybrid_search() runs both searches in one call and fuses the two ranked
lists with Reciprocal Rank Fusion (RRF), so you get one final ranking that
benefits from both signals.
"""

import os

from pymilvus import (
    MilvusClient,
    DataType,
    Function,
    FunctionType,
    AnnSearchRequest,
    RRFRanker,
)

COLLECTION_NAME = "hybrid_docs"
DENSE_DIM = 768  # Gemini "text-embedding-004" output dimension


DEFAULT_URI = "hybrid_rag.db"


def get_client(uri: str | None = None) -> MilvusClient:
    """
    Connects to Milvus. The same code talks to two very different backends:

      - a local file path  ("hybrid_rag.db")     -> Milvus Lite, embedded in this
        process, no server needed. Single-process only.
      - a server URI       ("http://localhost:19530", "http://milvus:19530")
        -> Milvus Standalone / cluster / Zilliz Cloud. Many clients at once.

    Resolution order: explicit `uri` arg -> MILVUS_ADDRESS env var -> DEFAULT_URI.
    MILVUS_TOKEN (e.g. "root:Milvus" or a Zilliz API key) is passed if set.
    (The env var is deliberately NOT called MILVUS_URI: pymilvus reads that
    name itself for its ORM default connection and rejects file paths in it.)
    """
    uri = uri or os.environ.get("MILVUS_ADDRESS") or DEFAULT_URI
    token = os.environ.get("MILVUS_TOKEN", "")
    return MilvusClient(uri=uri, token=token) if token else MilvusClient(uri=uri)


def is_lite(client: MilvusClient) -> bool:
    """True when the client is backed by an embedded Milvus Lite file."""
    uri = os.environ.get("MILVUS_ADDRESS") or DEFAULT_URI
    return not uri.startswith(("http://", "https://", "tcp://", "unix:"))


def ensure_loaded(client: MilvusClient):
    """
    Loads the collection into memory if it exists. Needed whenever a
    collection was created by another process (server.py / inspect_db.py
    opening a Lite file, or any client against Standalone).
    """
    if client.has_collection(COLLECTION_NAME):
        client.load_collection(COLLECTION_NAME)


def create_collection(client: MilvusClient, drop_existing: bool = True):
    if client.has_collection(COLLECTION_NAME):
        if drop_existing:
            client.drop_collection(COLLECTION_NAME)
        else:
            return

    schema = client.create_schema(auto_id=True)
    schema.add_field("id", DataType.INT64, is_primary=True, auto_id=True)
    schema.add_field("doc_id", DataType.VARCHAR, max_length=64)
    # enable_analyzer=True lets Milvus tokenize this field for BM25
    schema.add_field("text", DataType.VARCHAR, max_length=4000, enable_analyzer=True)
    schema.add_field("modality", DataType.VARCHAR, max_length=16)   # "text", "audio", "image" or "video"
    schema.add_field("source", DataType.VARCHAR, max_length=256)    # e.g. "test_data.json" or "alert.wav"
    schema.add_field("dense", DataType.FLOAT_VECTOR, dim=DENSE_DIM)
    schema.add_field("sparse", DataType.SPARSE_FLOAT_VECTOR)

    # This function runs INSIDE Milvus: every time you insert/search "text",
    # Milvus tokenizes it and computes BM25 term weights into "sparse"
    # automatically. You never compute BM25 yourself.
    bm25_function = Function(
        name="bm25_on_text",
        input_field_names=["text"],
        output_field_names=["sparse"],
        function_type=FunctionType.BM25,
    )
    schema.add_function(bm25_function)

    index_params = client.prepare_index_params()
    index_params.add_index(field_name="dense", index_type="AUTOINDEX", metric_type="COSINE")
    # SPARSE_INVERTED_INDEX explicitly, rather than AUTOINDEX, for the BM25
    # sparse field — AUTOINDEX has a known Milvus Lite bug that breaks
    # load_collection() on small datasets when a DB is reopened in a new
    # process (see: https://github.com/milvus-io/milvus-lite issues re:
    # "vector column must be FixedSizeList, got binary").
    index_params.add_index(field_name="sparse", index_type="SPARSE_INVERTED_INDEX", metric_type="BM25")

    client.create_collection(COLLECTION_NAME, schema=schema, index_params=index_params)


def insert_documents(client: MilvusClient, docs: list[dict], embed_fn):
    """
    docs: list of {"id": str, "text": str, "modality": "text"|"audio"|"image"|"video", "source": str}
          (modality/source are optional, default to "text" / "unknown")
    embed_fn: text -> list[float] (Gemini embedding call)

    For audio, "text" should already be the transcript produced upstream by
    gemini_client.transcribe_audio() — this function treats it exactly like
    any other document from that point on.
    """
    rows = []
    for d in docs:
        rows.append(
            {
                "doc_id": d["id"],
                "text": d["text"],
                "modality": d.get("modality", "text"),
                "source": d.get("source", "unknown"),
                "dense": embed_fn(d["text"]),
                # "sparse" is NOT provided — Milvus computes it via the BM25 function
            }
        )
    client.insert(COLLECTION_NAME, rows)
    client.flush(COLLECTION_NAME)


def hybrid_search(
    client: MilvusClient,
    query_text: str,
    query_dense_vector: list[float],
    top_k: int = 3,
    dense_weight_limit: int = 10,
    sparse_weight_limit: int = 10,
):
    """
    Runs dense (semantic) search and BM25 (keyword) search in parallel,
    then fuses the two rankings with RRF (Reciprocal Rank Fusion).
    RRF just says: "a document that ranks high in EITHER list gets a
    strong combined score" — no manual weight tuning needed.
    """
    dense_req = AnnSearchRequest(
        data=[query_dense_vector],
        anns_field="dense",
        param={"metric_type": "COSINE"},
        limit=dense_weight_limit,
    )
    sparse_req = AnnSearchRequest(
        data=[query_text],  # raw text in -> Milvus tokenizes + BM25-scores it
        anns_field="sparse",
        param={"metric_type": "BM25"},
        limit=sparse_weight_limit,
    )

    results = client.hybrid_search(
        COLLECTION_NAME,
        reqs=[dense_req, sparse_req],
        ranker=RRFRanker(),
        limit=top_k,
        output_fields=["doc_id", "text", "modality", "source"],
    )
    return [
        {
            "doc_id": hit["entity"]["doc_id"],
            "text": hit["entity"]["text"],
            "modality": hit["entity"]["modality"],
            "source": hit["entity"]["source"],
            "score": hit["distance"],
        }
        for hit in results[0]
    ]
